### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by ghost** [keyd-project/keyd-fork#2]
`autoconf` ->
```
configure.ac:14: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:42: error: possibly undefined macro: AM_PATH_PYTHON
configure.ac:51: error: possibly undefined macro: AM_CONDITIONAL
```

**Comment by rhansen** [comment]
You need to install GNU Automake before you can run `autoreconf -fviW all` to build `configure`.

Or you can download a distribution tarball with `configure` already built:
  * Once I make the first release you will be able to get a distribution tarball from the [releases page](https://github.com/keyd-project/keyd-fork/releases).
  * You can get a distribution tarball of the latest revision of the `main` branch from the CI build artifacts.  See:  https://nightly.link/keyd-project/keyd-fork/workflows/ci/main/distribution-tarball

**Comment by ghost** [comment]
What's wrong with make? Why not at least use cmake?

**Comment by rhansen** [comment]
Rolling your own build system is complicated and error prone.  There's a reason why Autoconf+Automake, CMake, etc. exist.

The phrase "at least use CMake" implies that CMake is better than Autoconf+Automake for this project, which I am skeptical of.  But mostly I chose Autoconf+Automake because that's what I'm familiar with.  If you think switching to CMake would improve this project, feel free to open a pull request.  Be sure to include plenty of rationale to justify the change.

**Comment by ghost** [comment]
Sorry if I sounded rude, now that I read my own messages. `make` was just trivial to use for end user like me, I'm also very familiar with cmake. Autoconf is just weird, and there's a common opinion that it shouldn't be used without a good reason. Anyway I'm closing this.
